# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/SwitchFrequency.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/halt.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/RegFileWrite.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/RegFiletoALU.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/RegFileRead.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/regfile.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/pc.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/npc.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/insturctionDecoder.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/IM.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/extend.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/DM.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/divider.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/display.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/decodShowInDisplay.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/counter.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/ALU.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/controller.v
  C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/sources_1/new/TopLayer.v
}
read_xdc C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/CurriculumDesign-PrinciplesOfComputerOrganization-master/single_circle/cpu.srcs/constrs_1/new/constraint.xdc]

synth_design -top TopLayer -part xc7a100tcsg324-1
write_checkpoint -noxdef TopLayer.dcp
catch { report_utilization -file TopLayer_utilization_synth.rpt -pb TopLayer_utilization_synth.pb }
